services:
  - type: static
    name: marya
    runtime: static
    repo: https://github.com/parkdaebog-spec/marya.git
    branch: marya
    publishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /marya.html
